In [1]:
import numpy as np


In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#2D Array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
#3D Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
#dtype
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
#np.arange
np.arange(1,5)


array([1, 2, 3, 4])

In [9]:
#with reshape
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#np.ones and np.zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#np.random
np.random.random((2,2))

array([[0.92944227, 0.78232959],
       [0.53533442, 0.5737185 ]])

In [12]:
#np.linspace
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [13]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes


In [15]:
a1 = np.arange(10)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [16]:
#ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [17]:
#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [18]:
#size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [20]:
#itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


Changing Datatypes

In [22]:
#astype
a1.astype(np.float32)
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [25]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
#scalar operations
#arithmetic
a1 * 2
a2 ** 2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [28]:
#relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
#vector operations
#arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])